"""empty message

Revision ID: 57a03d098b8c
Revises: 7798aa751131
Create Date: 2021-07-02 15:49:52.226237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a03d098b8c'
down_revision = '7798aa751131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('answers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'answers')
    # ### end Alembic commands ###
