"""empty message

Revision ID: 7798aa751131
Revises: 500c4fd28507
Create Date: 2021-05-12 15:22:32.208978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7798aa751131'
down_revision = '500c4fd28507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('component', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'component')
    # ### end Alembic commands ###
